<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Override in AnalogGridControlPlugin.csproj.user file -->
    <SpaceEngineersBin64>/path/to/SteamLibrary/steamapps/common/SpaceEngineers/Bin64</SpaceEngineersBin64>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="HarmonyLib">
      <Private>false</Private>
      <HintPath>$(Pulsar)/Libraries/Legacy/0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="HavokWrapper">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\HavokWrapper.dll</HintPath>
    </Reference>
    <Reference Include="ProtoBuf.Net">
      <Private>false</Private>
      <HintPath>$(SpaceEngineersBin64)/ProtoBuf.Net.dll</HintPath>
    </Reference>
    <Reference Include="ProtoBuf.Net.Core">
      <Private>false</Private>
      <HintPath>$(SpaceEngineersBin64)/ProtoBuf.Net.Core.dll</HintPath>
    </Reference>
    <Reference Include="Sandbox.Common">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\Sandbox.Common.dll</HintPath>
    </Reference>
    <Reference Include="Sandbox.Game">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\Sandbox.Game.dll</HintPath>
    </Reference>
    <Reference Include="Sandbox.Graphics">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\Sandbox.Graphics.dll</HintPath>
    </Reference>
    <Reference Include="SharpDX">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\SharpDX.dll</HintPath>
    </Reference>
    <Reference Include="SharpDX.DirectInput">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\SharpDX.DirectInput.dll</HintPath>
    </Reference>
    <Reference Include="VRage">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\VRage.dll</HintPath>
    </Reference>
    <Reference Include="VRage.Game">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\VRage.Game.dll</HintPath>
    </Reference>
    <Reference Include="VRage.Library">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\VRage.Library.dll</HintPath>
    </Reference>
    <Reference Include="VRage.Math">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\VRage.Math.dll</HintPath>
    </Reference>
    <Reference Include="VRageMath">
      <Private>false</Private>
      <HintPath>$(SpaceEngineersBin64)/VRage.Math.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.34.1" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="protobuf-net" Version="3.2.56" />
    <PackageReference Include="protobuf-net.Core" Version="3.2.56" />
  </ItemGroup>

</Project>
